name: Get Subscription Daily

on:
  schedule:
    - cron: '0 0 * * *'  # 每天凌晨（UTC 时间）执行
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write

jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install pyYAML
      run: pip3 install pyYAML

    - name: Install other dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Collect Subscribe
      id: collect
      run: |
        cd aggregate
        python -u subscribe/collect.py
        cat /home/runner/work/aggregator/aggregator/aggregate/proxies.yaml
        echo "::set-output name=value::$(cat /home/runner/work/aggregator/aggregator/aggregate/proxies.yaml)"

    - name: Gist Write Action
      uses: sergeysova/gist-write-action@v1
      with:
        GITHUB_TOKEN: ${{ secrets.PRIVATE_TOKEN_AGGREGATOR }}
        gist_id: 1ca7ef662fdce2d9c3add3e9689d4659
        file_name: proxies.yaml
        content: ${{steps.collect.outputs.value}}
          
