name: Get Subscription Daily

on:
  schedule:
    - cron: '0 0 * * *'  # 每天凌晨（UTC 时间）执行
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write

jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install pyYAML
      run: pip3 install pyYAML

    - name: Install other dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Execute Python Script
      run: |
        cd aggregate
        python -u subscribe/collect.py

    - name: Gist Write Action
      # You may pin to the exact commit or the version.
      # uses: sergeysova/gist-write-action@0c014107a8b6ac1c6ab495d6253f3c00f9905737
      uses: sergeysova/gist-write-action@v1.0.0
      with:
        script: |
          const fs = require('fs');
          const proxies = fs.readFileSync('/home/runner/work/aggregator/aggregator/aggregate/proxies.yaml', 'utf8');
          const token = env.GH_TOKEN; // 从环境变量中获取 Gist 令牌
          const gistId = '1ca7ef662fdce2d9c3add3e9689d4659'; // 将此处替换为你的 Gist 的 ID
          const octokit = github.getOctokit(token);
          await octokit.gists.update({
            gist_id: gistId,
            files: {
              'proxies.yaml': {
                content: proxies
              }
            }
          });
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
