name: 测试

on:
  schedule:
    - cron: '0 0 * * *'  # 每天凌晨（UTC 时间）执行
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write

jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Collect Subscribe
      id: collect
      run: |
        cd aggregate
        echo "::set-output name=value::$(echo 'test')"

    - name: Gist Write Action
      uses: sergeysova/gist-write-action@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_AGGREGATOR }}
        gist_id: 7bcddb642d16d291959642fc60feec9b
        file_name: proxies.yaml
        content: ${{steps.collect.outputs.value}}
          
