name: 测试

on:
  schedule:
    - cron: '0 0 * * *'  # 每天凌晨（UTC 时间）执行
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write

jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Collect Subscribe
      id: collect
      run: |
        cd aggregate
        touch proxies.yaml
        echo 'test me' > proxies.yaml

    - name: Gist Write Action
      uses: sergeysova/gist-write-action@v1
      with:
        GITHUB_TOKEN: ${{ secrets.PRIVATE_TOKEN_AGGREGATOR }}
        gist_id: ${{ secrets.GIST_ID }}
        file_name: proxies.yaml
        content: ${{steps.collect.outputs.value}}

    - name: Create/Update Gist
      env:
        GH_TOKEN: ${{ secrets.PRIVATE_TOKEN_AGGREGATOR }}
      run: |
        cd aggregate
        echo $GH_TOKEN | gh auth login --with-token
        gh gist edit ${{ secrets.GIST_ID }} --add "proxies.yaml"
          
